<?php

/**
 * @file
 * Contains factorial_monitoring_connector.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function factorial_monitoring_connector_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the factorial_monitoring_connector module.
    case 'help.page.factorial_monitoring_connector':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Connects the drupal installation to the factorial monitoring system') . '</p>';
      return $output;

    default:
  }
}
