<?php
/**
 * @file
 *
 * All public methods/hooks to provide a connector to the factorial monitoring service.
 */

/**
 * Implementation of hook_menu().
 */
function factorial_monitoring_connector_menu() {
  return array(
    'admin/monitor-state' => array(
      'page callback' => 'factorial_monitoring_connector_get_results',
      'access arguments' => array('access content'),
      'type' => MENU_CALLBACK,
    ),
  );
}

/**
 * Get the client version.
 */
function factorial_monitoring_connector_get_client_version() {
  return '1.0';
}




/**
 * Implements the page callback. Collect all results and return them as JSON.
 */
function factorial_monitoring_connector_get_results() {
  $results = module_invoke_all('factorial_monitoring_collect_values');

  $return = array(
    'results' => $results,
    'version' => factorial_monitoring_connector_get_client_version(),
  );

  // Disable caching.
  drupal_page_is_cacheable(FALSE);

  // Create response.
  $json = json_encode($return);
  drupal_add_http_header('Content-Type', 'application/json; charset=utf-8');
  print($json);
  drupal_exit();
}


/**
 * Implementation of hook_factorial_monitoring_collect_values().
 */
function factorial_monitoring_connector_factorial_monitoring_collect_values() {
  $result = array();

  $base_path = drupal_get_path('module', 'factorial_monitoring_connector') . '/collectors';
  $dir = scandir($base_path);

  foreach ($dir as $file) {
    $parts = pathinfo($file);
    if (($file[0] == '.') || ($parts['extension'] != 'inc')) {
      continue;
    }

    require_once $base_path . '/' . $file;
    $callback = 'factorial_monitoring_connector_collect_' . $parts['filename'];
    $query = $callback();

    if (!empty($query)) {
      if (isset($query['value'])) {
        $query = array($query);
      }
      $result += $query;
    }
  }

  return $result;
}
